### ISSUE TITLE
Cannot read property 'container' of null

### ISSUE THREAD

**Issue by rowellx68** [aurelia/store#88] opened 2019-02-25 16:16 UTC
**I'm submitting a bug report**

* **Library Version:**
1.3.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.1

* **NPM Version:**
6.8.0

* **JSPM OR Webpack AND Version**
Webpack 4.27.0

* **Browser:**
Chrome 72

* **Language:**
TypeScript 3.3

**Current behavior:**
When a custom attribute relies on access to the `state`, it throws a `Cannot read property 'container' of null` when the element using the custom attribute is being rendered.

```js
// only override if prototype callback is a function
if (typeof originalCreated === "function" || originalCreated === undefined) {
    target.prototype.created = function created(_, view) {
        // here we relies on the fact that the class Store
        // has not been registered somewhere in one of child containers, instead of root container
        // if there is any issue with this approach, needs to walk all the way up to resolve from root
        // typically like invoking from global Container.instance
        $store = view.container.get(Store);
        if (originalCreated !== undefined) {
            return originalCreated.call(this, _, view);
        }
    };
}
```

The snippet above is where the error originates, specifically `$store = view.container.get(Store)`.

Sample code can be had here: https://github.com/rowellx68/aurelia-store-attribute-issue

It seems like the fix could be to check if the `view` object exists before we attempt to access the `container`.

**Expected/desired behavior:**

* **What is the expected behavior?**
As with version 1.3.2, custom attributes requiring access to the state should render/work.

**Comment by bigopon** [comment] 2019-02-25 20:07
@rowellx68 thanks for filing this. This is because custom attribute doesn't have their own view. We can fallback to owning view, which is the first parameter in `created` if `view` is null, and then fallback to global `Container` instance

**Comment by bigopon** [comment] 2019-02-25 20:08
@rowellx68 thanks for filing this. This is because custom attribute doesn't have their own view. We can fallback to owning view, which is the first parameter in `created` if `view` is null, and then fallback to global `Container` instance.

**Comment by zewa666** [comment] 2019-02-26 06:37
well originally the connectTo decorator was designed for custom elements in mind. So out of the box I wouldn't expect it to work with custom attributes. Nevertheless what @bigopon proposed could be a way around to do so. I'm just not sure whether we should really go that route or instead throw a more specific error to say that this decorator is not meant to be used for anything except custom elements.

**Comment by rowellx68** [comment] 2019-02-26 06:59
@bigopon @zewa666 thanks for the update. Any reason why it was only meant for custom elements? Or if it’s even valid to allow custom attributes access to the state?

**Comment by zewa666** [comment] 2019-02-26 10:19
the connectTo decorator originally was introduced to simplify the process of creating state subscriptions in VMs, so to say to make the every-days use case easier. Custom attributes are not something you'd typically make on a same level as custom elements and thus weren't the focus when building the decorator. Supporting custom attributes would be doable although they deviate a bit in their lifecycle. But the largest issue is that sooner or later people start to question why you can't use the decorator on a generic service class. And thats where this goes off-board as the decorator is heavily relying on the presence of lifecycle hooks.

**Comment by rowellx68** [comment] 2019-02-26 11:43
Right! I guess we will have to manually subscribe to the state changes as laid out [here](https://aurelia.io/docs/plugins/store#subscribing-to-the-stream-of-states).

Thanks for the clarification, and I'm happy for the ticket to be closed.

**Comment by zewa666** [comment] 2019-02-26 11:58
I'd like to keep that one open for a while. As said I'm not married to the current approach, so if there are others chiming in here we might have to rethink our strategy.

**Comment by zewa666** [comment] 2019-09-24 07:48
Since there hasn't been any other activity about this I'm going to close this one

**Closed by zewa666** 2019-09-24 07:48 UTC
