### ISSUE TITLE
Property 'pluck' does not exist on type 'Observable<State>'.

### ISSUE THREAD

**Issue by maxdobler** [aurelia/store#25] opened 2018-04-18 14:30 UTC
Hi, 

following lines throw an error in VS Code:

@connectTo<State>({
  selector: store => store.state.pluck("list")
})

VS Code says: "[ts] Property 'pluck' does not exist on type 'Observable<State>'."

Do you know why this can happen?
I created a new project today, with aurelia-cli, packaging is done by webpack 4. Your Plugin works with connectTO decorator, but I can't use the pluck function...

**Comment by zewa666** [comment] 2018-04-22 11:54
@maxdobler did you manage to get it working?

**Comment by maxdobler** [comment] 2018-04-22 14:28
I have this line in main.ts. But it doesn't help. What exactly do I have to import and where?

`import { pluck } from "rxjs/operator/pluck";`

**Comment by maxdobler** [comment] 2018-04-22 14:34
ok, I got it! :)

I have to import the typescript Inerface for pluck:

`import "rxjs/add/operator/pluck";`

**Comment by zewa666** [comment] 2018-04-22 18:01
Yep patched imports, as they are patching the observable with additional features, are the way. More recently lettable operators would be another option.

**Comment by ben-girardet** [comment] 2018-05-30 08:11
I'm running into the same issue but I can't make it work. I'm using aurelia-store in an Aurelia CLI built with webpack project. Do I only need to add 

```
import "rxjs/add/operator/pluck";
```

And if yes, were exactly ?

**Comment by Belpois** [comment] 2018-05-30 08:15
@ben-girardet Pluck is available under `import { pluck } "rxjs/operators";`

Usage:
```ts
store.pipe(
   pluck("")
);
```

**Comment by ben-girardet** [comment] 2018-05-30 08:26
Thanks for your help, however it still doesn't work. Here is my View Model code:

```
...
import { Store, connectTo } from 'aurelia-store';
import { State } from '../../interfaces/state';
import { pluck } from 'rxjs/operators';

@inject(Element, Store, Router, App, NewInstance.of(ValidationController))
@connectTo<State>({
  selector: (store) => store.state.pipe(pluck('profile')),
  onChanged: "profileChanged"
})
export class Profile {
  public state: State;
  private subscription: any;
  ...
```

I've tried to use `.pipe()` on the `store` object, but it doesn't have a property pipe. When using it on the `state` object, the pipe property exists, but it doesn't accept the `pluck()` parameter:

**Comment by zewa666** [comment] 2018-05-30 12:21
wow this is a weird case ... for now just to continue change the selector line to read:

```typescript
selector: (store) => store.state.pipe(<any>pluck('profile')),
```

Will take a closer look to it

**Comment by zewa666** [comment] 2018-05-30 13:56
hey @ben-girardet are you trying that out inside a CLI, Webpack based app? I couldn't reproduce the issue within my projects or a CLI requirejs based project. So I suspect it could be something related to dependencies used within the Webpack build

**Comment by ben-girardet** [comment] 2018-05-30 14:17
Thanks for this clarification. May I then ask a question (a little off topic). In the code (see below) there is a comment suggesting that the handler would have access to the previous state. That would allow the application to compare previous and current state (in the plucked value) to see if any relevant changes occurred when it receives the onChanged callback. But if I understand the code correctly, for now only the current (new) state is sent to the callback. Is it correct ? If yes, any chance to get both the previous and the current state on callbacks ?

https://github.com/aurelia/store/blob/48afdf4f28796b925d977f2f6d6f321e27b29bdc/src/decorator.ts#L53

**Comment by zewa666** [comment] 2018-05-30 14:32
as the comment suggests, the handler is called before assigning the target. You have the possibility to check for `this.state` and the passed in parameter `state`. Take a look at [this test](https://github.com/aurelia/store/blob/master/test/unit/decorator.spec.ts#L334) showing that behaviour.

**Comment by zewa666** [comment] 2018-05-30 14:34
Meanwhile, @ben-girardet can you just create a minimal repro sample - as github repo - so we can work from there to get the above issue addressed?

**Comment by ben-girardet** [comment] 2018-05-30 15:10
Here you go @zewa666 
https://github.com/ben-girardet/aurelia-store-app

**Comment by Belpois** [comment] 2018-05-30 15:45
@ben-girardet I got your repo and managed to build and run it just fine.

![image](https://user-images.githubusercontent.com/8214583/40731318-0bbfac54-6431-11e8-9f6b-ff1c7ca45229.png)

and after I added the `aurelia-store` reference to `main.ts` the site also rendered fine including the console log you included `profileChanged`

![image](https://user-images.githubusercontent.com/8214583/40731389-36497996-6431-11e8-90d3-13393159c7df.png)

**Comment by ben-girardet** [comment] 2018-05-30 16:04
That's interesting !!

I've built the repo from scratch an hour ago, including running a fresh `npm install`.
How did you run the application? Did you use the `au` command from aurelia-cli ?

Here is my VS code (including the error) and my terminal when running the app with `au run --watch`

<img width="1280" alt="capture d ecran 2018-05-30 a 17 59 27" src="https://user-images.githubusercontent.com/4275071/40732533-cd73d062-6433-11e8-8ffe-ca4eb34abbab.png">

<img width="1017" alt="capture d ecran 2018-05-30 a 18 02 36" src="https://user-images.githubusercontent.com/4275071/40732541-d0b677de-6433-11e8-8f0c-b03c038acdbf.png">

**Comment by Belpois** [comment] 2018-05-30 16:13
First time I ran the application I used `npm start` and now I ran it using `au run --watch` and it still runs correctly.

**Comment by zewa666** [comment] 2018-05-30 19:15
I've tracked it down so far as well and inquirer is a dependency from webpack-cli. So not a lot one can do about it. Agree it definitely has to be a version mismatch just why does the wrong one pierce through and more interestingly why does it work for you @Belpois?

**Comment by zewa666** [comment] 2018-05-30 19:26
Im not at a PC currently but I suspect that au new + letting it automatically Install all dependencies might be the issue. If we skip that and manually do a full npm install that might solve it. Another interesting thing would be to see how yarn behaves

**Comment by ben-girardet** [comment] 2018-05-30 19:57
The way I did my install was:

* `au new`
* answered _no_ when asked to install dependencies automatically
* `cd aurelia-store-app`
* `npm install`
* `npm install aurelia-store`

**Comment by zewa666** [comment] 2018-05-30 20:32
Hmm and the node, npm and cli version are?

**Comment by Belpois** [comment] 2018-05-31 05:30
@ben-girardet I followed you instruction and the error popped up, a quick clean to the node modules folder and a fresh install cleared up the issue (not really a fix though)

@zewa666 I created a new install following @ben-girardet instructions using `yarn` and it works the first time round. I bet that `yarn` go through all the dependencies again and clears up any other version of the same library.

Maybe adding a `peerDependency` in aurelia-store for `rxjs@^6.2.0` would aid NPM to check previous dependencies installed.

**Comment by ben-girardet** [comment] 2018-05-31 07:02
@Belpois You're right, after a clean of node_modules and fresh `npm install` everything work fine. Such a strange thing...

**Comment by zewa666** [comment] 2018-05-31 08:32
@Belpois the peerdependency declaration might help. Can you give it a try?

**Comment by Belpois** [comment] 2018-05-31 20:37
@ben-girardet I tried using peer-dependencies but I still got the error, I will look into it a bit more hopefully tomorrow.

**Comment by zewa666** [comment] 2018-06-16 08:15
@doktordirk did the peer-deps work for you for the Store Plugin as described in your linked issue?

**Comment by doktordirk** [comment] 2018-06-16 08:27
on the list today

**Comment by doktordirk** [comment] 2018-06-16 11:12
hav no problem here now in the first place (since i'm on rxjs6 anyways as does this plugin). did work for the other plugin with had rxjs5 as dependency. maybe that one was what caused the problem here. anyways, i belevieve peerDep is the way to go as such. i never got actually why not all deps are peerDeps. making them deps if there can be side effects is just asking for trouble. (just also have them as dev deps for testing)

**Comment by zewa666** [comment] 2018-10-01 12:37
What I've experienced so far is that the issue is most often solved by making sure you don't use any too old version of ts/rxjs by yourself and keep it aligned with the plugin, dropping the `node_modules` folder and `package-lock.json`and a subsequent `npm install` seem to properly fix it.

Closing this one for know we can reopen if we have more insights

**Closed by zewa666** 2018-10-01 12:37 UTC
Labels: question
